name    'alkivi-rsyslog'
version '0.1.1'
source 'https://github.com/alkivi-sas/puppet-rsyslog'
author 'alkivi'
license 'LGPLv3'
summary 'Controls rsyslog server'
description 'Setup rsyslog server to act as main or slave'
project_page 'https://github.com/alkivi-sas/puppet-rsyslog'
dependency 'puppetlabs/stdlib', '>=3.0.0'
dependency 'puppetlabs/concat', '>=1.0.0'
